### ISSUE TITLE
To display the form after sending it the PHPSESSID cookie must be deleted

### ISSUE THREAD

**Issue by netzarbeiter** [Tastaturberuf/contao-form-content-bundle#1]
Thank you for this bundle.

I have activated «Show content elements after submitting» and selected the mode «one time».

After sending the request, the content elements shows up.

After choosing the mode «one time» I expect that the form comes back after reloading the website. To get back the form, I have to delete the PHPSESSID cookie. 

Is this a bug or a feature?

Contao 4.9.11 / Bundle 1.0.3

**Comment by Tastaturberuf** [comment]
its a bug. this behavior is only expected on `session`-mode. I will test and fix this ASAP.

**Comment by Tastaturberuf** [comment]
thanks @netzarbeiter

**Comment by netzarbeiter** [comment]
Thank you, for fixing the bug. Works now as expected.
